export type MemoryItem = {
  id: string;
  category: string;
  categoryColor: string;
  title: string;
  summary: string;
  tags: string[];
  confidence: number;
  isSensitive: boolean;
  ocrText?: string;
  dateAdded: string;
  bgColor: string;
  textColor: string;
  accentColor: string;
  icon: string;
};

export type Collection = {
  id: string;
  name: string;
  icon: string;
  count: number;
  insight: string;
  accentColor: string;
  bgColor: string;
  category: string;
};

export const COLORS = {
  bg: '#070806',
  surface: '#11120F',
  surfaceAlt: '#181A14',
  surfaceGreen: '#10180F',
  ivory: '#F8F1E7',
  textPrimary: '#F8F1E7',
  textSecondary: '#A49D90',
  textTertiary: '#625D54',
  textDark: '#11120F',
  lime: '#C8FF2E',
  amber: '#F5A623',
  cyan: '#35D5D5',
  red: '#E85D4A',
  border: 'rgba(245,240,232,0.12)',
  borderMuted: 'rgba(245,240,232,0.07)',
};

export const mockMemories: MemoryItem[] = [
  {
    id: '1',
    category: 'Coding',
    categoryColor: COLORS.cyan,
    title: 'React Hook Error',
    summary: 'Invalid hook call. Hooks can only be called inside a function component. Possible mismatch of React versions.',
    tags: ['React', 'JavaScript', 'Debugging'],
    confidence: 97,
    isSensitive: false,
    ocrText: 'Error: Invalid hook call. Hooks can only be called inside of the body of a function component.',
    dateAdded: '2 hours ago',
    bgColor: '#0D1A1F',
    textColor: '#3ECFCF',
    accentColor: COLORS.cyan,
    icon: 'Code',
  },
  {
    id: '2',
    category: 'Coding',
    categoryColor: COLORS.cyan,
    title: 'TypeScript Generic Utility',
    summary: 'A utility type for deep partial objects with recursive typing pattern.',
    tags: ['TypeScript', 'Generics', 'Utility'],
    confidence: 94,
    isSensitive: false,
    ocrText: 'type DeepPartial<T> = T extends object ? { [P in keyof T]?: DeepPartial<T[P]>; } : T;',
    dateAdded: '1 day ago',
    bgColor: '#0D1A1F',
    textColor: '#3ECFCF',
    accentColor: COLORS.cyan,
    icon: 'Code',
  },
  {
    id: '3',
    category: 'Coding',
    categoryColor: COLORS.cyan,
    title: 'CSS Grid Layout Pattern',
    summary: 'Advanced CSS grid with named template areas for dashboard layout.',
    tags: ['CSS', 'Grid', 'Layout'],
    confidence: 91,
    isSensitive: false,
    ocrText: 'grid-template-areas: "header header" "sidebar main" "footer footer"',
    dateAdded: '3 days ago',
    bgColor: '#0D1A1F',
    textColor: '#3ECFCF',
    accentColor: COLORS.cyan,
    icon: 'Code',
  },
  {
    id: '4',
    category: 'Startup Ideas',
    categoryColor: COLORS.lime,
    title: 'AI SaaS Idea',
    summary: 'A saved product idea about AI workflow automation for non-technical founders. Recurring revenue model.',
    tags: ['AI', 'SaaS', 'Founder'],
    confidence: 88,
    isSensitive: false,
    ocrText: 'Idea: AI-powered workflow builder for ops teams. No code. Auto-detects bottlenecks.',
    dateAdded: '5 hours ago',
    bgColor: '#141A0A',
    textColor: '#C8F135',
    accentColor: COLORS.lime,
    icon: 'Rocket',
  },
  {
    id: '5',
    category: 'Startup Ideas',
    categoryColor: COLORS.lime,
    title: 'B2B Data Marketplace',
    summary: 'Marketplace for verified business datasets. Privacy-first, API-first approach.',
    tags: ['B2B', 'Data', 'Marketplace'],
    confidence: 85,
    isSensitive: false,
    ocrText: 'Business idea: verified data marketplace. Companies sell anonymized datasets to researchers.',
    dateAdded: '1 day ago',
    bgColor: '#141A0A',
    textColor: '#C8F135',
    accentColor: COLORS.lime,
    icon: 'Rocket',
  },
  {
    id: '6',
    category: 'Startup Ideas',
    categoryColor: COLORS.lime,
    title: 'Sleep Tech App Concept',
    summary: 'Mobile app that uses phone microphone to detect sleep stages and optimize wake time.',
    tags: ['Health', 'Mobile', 'Sleep'],
    confidence: 82,
    isSensitive: false,
    ocrText: 'App concept: sleep stage detection via mic. Smart alarm. $9.99/mo. Market: 40M insomniacs.',
    dateAdded: '2 days ago',
    bgColor: '#141A0A',
    textColor: '#C8F135',
    accentColor: COLORS.lime,
    icon: 'Rocket',
  },
  {
    id: '7',
    category: 'Quotes',
    categoryColor: COLORS.amber,
    title: 'Naval on Wealth',
    summary: '"Seek wealth, not money or status. Wealth is having assets that earn while you sleep."',
    tags: ['Naval', 'Wealth', 'Philosophy'],
    confidence: 99,
    isSensitive: false,
    ocrText: 'Seek wealth, not money or status. Wealth is having assets that earn while you sleep. — Naval Ravikant',
    dateAdded: '1 week ago',
    bgColor: '#1A1408',
    textColor: '#F5A623',
    accentColor: COLORS.amber,
    icon: 'Quotes',
  },
  {
    id: '8',
    category: 'Quotes',
    categoryColor: COLORS.amber,
    title: 'Feynman on Understanding',
    summary: '"If you can\'t explain it simply, you don\'t understand it well enough." — Richard Feynman',
    tags: ['Feynman', 'Learning', 'Clarity'],
    confidence: 99,
    isSensitive: false,
    ocrText: 'If you cant explain it simply, you dont understand it well enough. — Richard Feynman',
    dateAdded: '2 weeks ago',
    bgColor: '#1A1408',
    textColor: '#F5A623',
    accentColor: COLORS.amber,
    icon: 'Quotes',
  },
  {
    id: '9',
    category: 'Books',
    categoryColor: '#9B8EFF',
    title: 'Atomic Habits Note',
    summary: 'Identity-based habit formation: become the person who does the action, not someone trying to achieve a result.',
    tags: ['Habits', 'Learning', 'Productivity'],
    confidence: 96,
    isSensitive: false,
    ocrText: 'Every action you take is a vote for the type of person you wish to become. — James Clear',
    dateAdded: '3 days ago',
    bgColor: '#120F1F',
    textColor: '#9B8EFF',
    accentColor: '#9B8EFF',
    icon: 'BookOpen',
  },
  {
    id: '10',
    category: 'Books',
    categoryColor: '#9B8EFF',
    title: 'Zero to One Highlight',
    summary: 'Competition is for losers. If you\'re competing, you\'re in a commodity market. Create a monopoly.',
    tags: ['Thiel', 'Startups', 'Strategy'],
    confidence: 94,
    isSensitive: false,
    ocrText: 'Competition is for losers. — Peter Thiel, Zero to One',
    dateAdded: '5 days ago',
    bgColor: '#120F1F',
    textColor: '#9B8EFF',
    accentColor: '#9B8EFF',
    icon: 'BookOpen',
  },
  {
    id: '11',
    category: 'Food',
    categoryColor: '#FF8C5A',
    title: 'Burger Place',
    summary: 'Smash burger spot in Bandra. Wagyu patty. Saved as "try this weekend".',
    tags: ['Burger', 'Restaurant', 'Dinner'],
    confidence: 89,
    isSensitive: false,
    dateAdded: '4 days ago',
    bgColor: '#1A0F0A',
    textColor: '#FF8C5A',
    accentColor: '#FF8C5A',
    icon: 'ForkKnife',
  },
  {
    id: '12',
    category: 'Food',
    categoryColor: '#FF8C5A',
    title: 'Ramen Recipe',
    summary: 'Tonkotsu broth recipe with 18-hour pork bone simmering instructions and tare seasoning.',
    tags: ['Ramen', 'Recipe', 'Japanese'],
    confidence: 93,
    isSensitive: false,
    ocrText: 'Tonkotsu base: 2kg pork bones. Blanch, rinse, simmer 18hrs. Add tare before serving.',
    dateAdded: '1 week ago',
    bgColor: '#1A0F0A',
    textColor: '#FF8C5A',
    accentColor: '#FF8C5A',
    icon: 'ForkKnife',
  },
  {
    id: '13',
    category: 'Receipts',
    categoryColor: '#6BD4A0',
    title: 'Payment Receipt',
    summary: 'AWS invoice for ₹4,892. Services: EC2, S3, CloudFront. Billing period: April 2025.',
    tags: ['Payment', 'AWS', 'Finance'],
    confidence: 98,
    isSensitive: false,
    ocrText: 'Amazon Web Services Invoice. Total: ₹4,892.00. Due: April 30, 2025.',
    dateAdded: '2 weeks ago',
    bgColor: '#0A1A12',
    textColor: '#6BD4A0',
    accentColor: '#6BD4A0',
    icon: 'Receipt',
  },
  {
    id: '14',
    category: 'Receipts',
    categoryColor: '#6BD4A0',
    title: 'Figma Subscription',
    summary: 'Figma Professional plan receipt. ₹1,999/month billed annually.',
    tags: ['Figma', 'Subscription', 'Design'],
    confidence: 97,
    isSensitive: false,
    ocrText: 'Figma Inc. Professional Plan. ₹1,999.00/month. Next billing: May 15, 2025.',
    dateAdded: '3 weeks ago',
    bgColor: '#0A1A12',
    textColor: '#6BD4A0',
    accentColor: '#6BD4A0',
    icon: 'Receipt',
  },
  {
    id: '15',
    category: 'Travel',
    categoryColor: '#5AC8E8',
    title: 'Manali Itinerary',
    summary: 'A 5-day Manali trip plan. Rohtang Pass, Solang Valley, Old Manali cafes.',
    tags: ['Travel', 'Manali', 'Mountains'],
    confidence: 91,
    isSensitive: false,
    ocrText: 'Day 1: Arrive. Day 2: Rohtang Pass. Day 3: Solang Valley. Day 4: Old Manali. Day 5: Return.',
    dateAdded: '1 month ago',
    bgColor: '#0A1520',
    textColor: '#5AC8E8',
    accentColor: '#5AC8E8',
    icon: 'MapPin',
  },
  {
    id: '16',
    category: 'Memes',
    categoryColor: '#E87DE8',
    title: 'Programmer Meme',
    summary: 'The classic "it works on my machine" meme. Ship the machine.',
    tags: ['Meme', 'Programming', 'Humor'],
    confidence: 87,
    isSensitive: false,
    dateAdded: '5 days ago',
    bgColor: '#1A0A1A',
    textColor: '#E87DE8',
    accentColor: '#E87DE8',
    icon: 'Smiley',
  },
  {
    id: '17',
    category: 'Documents',
    categoryColor: '#D4C4A0',
    title: 'NDA Template',
    summary: 'Non-disclosure agreement template for freelance projects. Mutual NDA, 2-year term.',
    tags: ['Legal', 'NDA', 'Contract'],
    confidence: 96,
    isSensitive: false,
    ocrText: 'MUTUAL NON-DISCLOSURE AGREEMENT. This Agreement entered into as of [Date]...',
    dateAdded: '2 weeks ago',
    bgColor: '#1A1810',
    textColor: '#D4C4A0',
    accentColor: '#D4C4A0',
    icon: 'FileText',
  },
  {
    id: '18',
    category: 'Sensitive',
    categoryColor: COLORS.red,
    title: 'API Key Screenshot',
    summary: 'A screenshot that may contain sensitive API credentials and access tokens.',
    tags: ['Security', 'API Key', 'Private'],
    confidence: 99,
    isSensitive: true,
    ocrText: 'sk-proj-xxxxxxxxxxxxxxxxxxxx [REDACTED FOR PRIVACY]',
    dateAdded: '1 week ago',
    bgColor: '#1A0A0A',
    textColor: '#E85D4A',
    accentColor: COLORS.red,
    icon: 'ShieldWarning',
  },
];

export const collections: Collection[] = [
  {
    id: 'coding',
    name: 'Coding',
    icon: 'Code',
    count: 8,
    insight: '3 React, 2 TypeScript, CSS patterns',
    accentColor: COLORS.cyan,
    bgColor: '#0D1A1F',
    category: 'Tech',
  },
  {
    id: 'startup',
    name: 'Startup Ideas',
    icon: 'Rocket',
    count: 12,
    insight: 'Most mentioned: AI, SaaS, mobile',
    accentColor: COLORS.lime,
    bgColor: '#141A0A',
    category: 'Business',
  },
  {
    id: 'books',
    name: 'Books',
    icon: 'BookOpen',
    count: 9,
    insight: 'Atomic Habits, Zero to One, PSYCH:ON',
    accentColor: '#9B8EFF',
    bgColor: '#120F1F',
    category: 'Learning',
  },
  {
    id: 'quotes',
    name: 'Quotes',
    icon: 'Quotes',
    count: 17,
    insight: 'Naval, Feynman, Buffett, Marcus Aurelius',
    accentColor: COLORS.amber,
    bgColor: '#1A1408',
    category: 'Inspiration',
  },
  {
    id: 'food',
    name: 'Food',
    icon: 'ForkKnife',
    count: 21,
    insight: '14 restaurant saves, 7 recipes',
    accentColor: '#FF8C5A',
    bgColor: '#1A0F0A',
    category: 'Lifestyle',
  },
  {
    id: 'receipts',
    name: 'Receipts',
    icon: 'Receipt',
    count: 5,
    insight: '5 purchase records found',
    accentColor: '#6BD4A0',
    bgColor: '#0A1A12',
    category: 'Finance',
  },
  {
    id: 'study',
    name: 'Study Notes',
    icon: 'Student',
    count: 14,
    insight: '34 learning screenshots this month',
    accentColor: '#B0D4F0',
    bgColor: '#0A1018',
    category: 'Learning',
  },
  {
    id: 'fitness',
    name: 'Fitness',
    icon: 'Barbell',
    count: 7,
    insight: 'Workout plans, nutrition, PRs',
    accentColor: '#F0E040',
    bgColor: '#1A1A08',
    category: 'Lifestyle',
  },
  {
    id: 'travel',
    name: 'Travel',
    icon: 'MapPin',
    count: 11,
    insight: 'Manali, Goa, Bali planned',
    accentColor: '#5AC8E8',
    bgColor: '#0A1520',
    category: 'Lifestyle',
  },
  {
    id: 'memes',
    name: 'Memes',
    icon: 'Smiley',
    count: 34,
    insight: 'Dev memes, startup humor, random gold',
    accentColor: '#E87DE8',
    bgColor: '#1A0A1A',
    category: 'Fun',
  },
  {
    id: 'documents',
    name: 'Documents',
    icon: 'FileText',
    count: 6,
    insight: 'NDAs, invoices, templates',
    accentColor: '#D4C4A0',
    bgColor: '#1A1810',
    category: 'Work',
  },
  {
    id: 'sensitive',
    name: 'Sensitive',
    icon: 'ShieldWarning',
    count: 3,
    insight: '3 private screenshots need review',
    accentColor: COLORS.red,
    bgColor: '#1A0A0A',
    category: 'Private',
  },
];

export const searchSuggestions = [
  { id: '1', text: 'React code screenshots', icon: 'Code' },
  { id: '2', text: 'Food I saved recently', icon: 'ForkKnife' },
  { id: '3', text: 'Receipts from this month', icon: 'Receipt' },
  { id: '4', text: 'Quotes about discipline', icon: 'Quotes' },
  { id: '5', text: 'Screenshots with phone numbers', icon: 'Phone' },
  { id: '6', text: 'AI startup ideas', icon: 'Rocket' },
  { id: '7', text: 'Travel plans', icon: 'MapPin' },
];

export const weeklyStats = {
  totalIndexed: 128,
  screenshotsPercent: 42,
  startupIdeas: 14,
  receiptsDetected: 5,
  sensitiveProtected: 3,
  forgottenResurfaced: 12,
  learningScreenshots: 34,
  topCategory: 'Coding',
};
